"""initial_schema

Revision ID: 5568ead91372
Revises: 
Create Date: 2026-09-21 00:14:06.657390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5568ead91372'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('estimated_weeks', sa.Integer(), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monogram', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('process_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('estimated_time', sa.String(), nullable=True),
    sa.Column('total_topics', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.String(), nullable=True),
    sa.Column('current_semester', sa.String(), nullable=True),
    sa.Column('drive_cycle', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('preferred_job_type', sa.String(), nullable=True),
    sa.Column('location_preference', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('resource_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('concept_key', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('set_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('problem_statement', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_option', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['practice_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_career_paths',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('career_path_id', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'career_path_id')
    )
    op.create_table('profile_skill_baselines',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('programming', sa.String(), nullable=True),
    sa.Column('dsa', sa.String(), nullable=True),
    sa.Column('sql', sa.String(), nullable=True),
    sa.Column('core_cs', sa.String(), nullable=True),
    sa.Column('aptitude', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('career_path_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_rubric', sa.String(), nullable=True),
    sa.Column('total_stages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_company_targets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('user_practice_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('set_id', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['practice_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('learning_reminders', sa.Boolean(), nullable=True),
    sa.Column('practice_alerts', sa.Boolean(), nullable=True),
    sa.Column('company_alerts', sa.Boolean(), nullable=True),
    sa.Column('weekly_digest', sa.Boolean(), nullable=True),
    sa.Column('interface_density', sa.String(), nullable=True),
    sa.Column('code_theme', sa.String(), nullable=True),
    sa.Column('profile_visibility', sa.String(), nullable=True),
    sa.Column('telemetry_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_subject_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('topics_completed', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject')
    )
    op.create_table('roadmap_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('roadmap_id', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resource_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('last_page_read', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    op.create_table('user_topic_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['learning_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    op.create_table('user_roadmap_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('roadmap_id', sa.String(), nullable=False),
    sa.Column('current_stage_id', sa.String(), nullable=True),
    sa.Column('completed_stages', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_stage_id'], ['roadmap_stages.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'roadmap_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roadmap_progress')
    op.drop_table('user_topic_progress')
    op.drop_table('user_resource_progress')
    op.drop_table('roadmap_stages')
    op.drop_table('user_subject_progress')
    op.drop_table('user_settings')
    op.drop_table('user_practice_attempts')
    op.drop_table('user_company_targets')
    op.drop_table('roadmaps')
    op.drop_table('resources')
    op.drop_table('profile_skill_baselines')
    op.drop_table('profile_career_paths')
    op.drop_table('practice_questions')
    op.drop_table('learning_topics')
    op.drop_table('company_roles')
    op.drop_table('activity_events')
    op.drop_table('resource_categories')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('practice_sets')
    op.drop_table('learning_modules')
    op.drop_table('companies')
    op.drop_table('career_paths')
    # ### end Alembic commands ###
