"""update_learning_schema

Revision ID: 8a014505bb9e
Revises: 30d943549662
Create Date: 2026-09-21 13:04:35.761484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a014505bb9e'
down_revision: Union[str, Sequence[str], None] = '30d943549662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_subjects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_subjects_slug'), ['slug'], unique=True)

    op.create_table('user_learning_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['learning_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_learning_progress_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_learning_progress_user_id'), ['user_id'], unique=False)


    with op.batch_alter_table('learning_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_learning_modules_subject_id_learning_subjects', 'learning_subjects', ['subject_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_modules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_learning_modules_subject_id_learning_subjects', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('display_order')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('slug')
        batch_op.drop_column('subject_id')


    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_learning_progress_topic_id'))

    op.drop_table('user_learning_progress')
    with op.batch_alter_table('learning_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_subjects_slug'))

    op.drop_table('learning_subjects')
    # ### end Alembic commands ###
