"""add_resume_analysis

Revision ID: 9e1a2c3d4f5b
Revises: 8a014505bb9e
Create Date: 2026-09-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1a2c3d4f5b'
down_revision: Union[str, Sequence[str], None] = '8a014505bb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resume_analyses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('company', sa.String(), nullable=False),
        sa.Column('company_type', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('custom_role', sa.String(), nullable=True),
        sa.Column('job_description', sa.Text(), nullable=True),
        sa.Column('source_type', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('page_count', sa.Integer(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, default='pending'),
        sa.Column('current_stage', sa.String(), nullable=True),
        sa.Column('stage_state', sa.Text(), nullable=False),
        sa.Column('request_snapshot', sa.Text(), nullable=False),
        sa.Column('parsed_resume', sa.Text(), nullable=True),
        sa.Column('analysis_result', sa.Text(), nullable=True),
        sa.Column('error_code', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('failed_stage', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('failed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_resume_analyses_user_id_created_at',
        'resume_analyses',
        ['user_id', 'created_at'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resume_analyses_user_id_created_at', table_name='resume_analyses')
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###